"""
sqlgen/liquibase_xml.py

Generates Liquibase <changeSet> XML snippet(s) for load stored procedures.

Output is a snippet ready to append to:
  inflow-db-cst/changelog/release_scripts/{ClientId}_{ClientName}.xml

Pattern matches:
  inflow-db-cst/changelog/release_scripts/0005_PresbyterianHealthSystem.xml
"""

from __future__ import annotations

from .constants import SOURCE_TO_ENTITY_NAME


def generate(
    *,
    client_id: str,
    client_name: str,
    sproc_files: list[dict],
) -> str:
    """
    Generate Liquibase changeSet XML entries for one or more load sproc files.

    Parameters
    ----------
    client_id    : 4-digit client ID (e.g. '0073')
    client_name  : Client name (e.g. 'Ardent')
    sproc_files  : List of dicts with keys:
                   - source      : source type key (e.g. 'payroll')
                   - ds_number   : integer (e.g. 2)
                   (one entry per source file)

    Returns
    -------
    XML snippet string — append to the client's release_scripts XML file.
    """
    context = f"{client_id}_{client_name}"
    folder = f"{client_id}_{client_name}"

    entries: list[str] = []
    for f in sproc_files:
        entity = SOURCE_TO_ENTITY_NAME[f["source"]]
        nn = f"{f['ds_number']:02d}"
        sproc_name = f"cst.dl{nn}_{entity}"
        sproc_file = f"{sproc_name}.sql"
        changeset_id = f"{context}.{sproc_name}"
        rel_path = f"../database_objects/{folder}/Stored Procedures/{sproc_file}"

        entries.append(f"""\
<changeSet id="{changeset_id}"
           author="Liquibase CST" context="{context}" runOnChange="true">
  <sqlFile encoding="UTF-8"
           path="{rel_path}"
           relativeToChangelogFile="true" splitStatements="true" stripComments="false" endDelimiter="GO" />
</changeSet>""")

    inner = "\n\n".join(entries)
    return (
        f"<!-- Generated by TestFileReviewAutomation sqlgen"
        f" — append to release_scripts/{context}.xml -->\n"
        + inner
        + "\n"
    )
